---
language: node_js
node_js:
  - 4
  - 6
  - 7
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install: true
env:
  global:
    - USE_YARN=yes
matrix:
  include:
    - node_js: 0.10
    - node_js: 6
